import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';

import { AppComponent } from './app.component';
import { DashboardComponent } from './dashboard.component';
import { ProductComponent } from './products/product.component';
import { UpperValuePipe } from './products/upperValue.pipe';
import { AddValuePipe } from './products/addValue.pipe';
import { FilterProductPipe } from './products/filterText.pipe';
import { StarComponent } from './shared/star.component';
import { ProductService } from './products/product.service';
import { OrderComponent } from './orders/orders.component';
import { HomeComponent } from './home/home.component';
import { ProductDetailComponent } from './products/product-detail.component';
import { NotFoundComponent } from './shared/notFound.component';
import { ProductModule } from './products/product.module';


@NgModule({
    // All Module will declare here
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        RouterModule.forRoot([
            {path: 'products', component: ProductComponent},
            {path: 'products/:id', component: ProductDetailComponent},
            {path: 'orders', component: OrderComponent },
            {path: 'home', component: HomeComponent },
            {path: '', redirectTo: 'home', pathMatch: 'full'},
            {path: '**', component: NotFoundComponent}

        ]),
        ProductModule
    ],
    // All Component & pipes
    declarations: [
        AppComponent,
        DashboardComponent,
        ProductComponent,
        UpperValuePipe,
        AddValuePipe,
        FilterProductPipe,
        StarComponent,
        OrderComponent,
        HomeComponent,
        ProductDetailComponent,
        NotFoundComponent
    ],
    // Only first component will come here
    bootstrap: [
        AppComponent
     ],
    // All Service / Injectable will come here
    providers: [
        ProductService
    ]
})

export class AppModule {

}
